import { NewsTodayResponseDto } from './dto/news-today-response.dto';

export function buildMockTodayNews(now = new Date()): NewsTodayResponseDto[] {
  const publishedAt = now.toISOString();
  return [
    {
      id: 'mock-bloqueo-el-alto',
      title: 'Bloqueo en El Alto afecta rutas principales',
      description: 'Vecinos reportan bloqueo temporal cerca de la Ceja de El Alto.',
      source: 'MAPIA demo',
      url: null,
      publishedAt,
      locationText: 'El Alto, La Paz, Bolivia',
      lat: -16.5048,
      lng: -68.1633,
      category: 'bloqueo',
      createdBy: 'rss',
      locationStatus: 'mock',
    },
    {
      id: 'mock-evento-la-paz',
      title: 'Evento cultural en La Paz',
      description: 'Actividad cultural abierta al publico en el centro paceño.',
      source: 'MAPIA demo',
      url: null,
      publishedAt,
      locationText: 'La Paz, Bolivia',
      lat: -16.4897,
      lng: -68.1193,
      category: 'evento',
      createdBy: 'usuario',
      locationStatus: 'mock',
    },
    {
      id: 'mock-corte-agua-cochabamba',
      title: 'Corte de agua en Cochabamba',
      description: 'Mantenimiento programado interrumpe el servicio en zonas cercanas.',
      source: 'MAPIA demo',
      url: null,
      publishedAt,
      locationText: 'Cochabamba, Bolivia',
      lat: -17.3895,
      lng: -66.1568,
      category: 'corte_servicio',
      createdBy: 'usuario',
      locationStatus: 'mock',
    },
    {
      id: 'mock-feria-santa-cruz',
      title: 'Feria de venta en Santa Cruz',
      description: 'Comerciantes anuncian feria con productos locales durante el dia.',
      source: 'MAPIA demo',
      url: null,
      publishedAt,
      locationText: 'Santa Cruz de la Sierra, Bolivia',
      lat: -17.7833,
      lng: -63.1821,
      category: 'venta',
      createdBy: 'usuario',
      locationStatus: 'mock',
    },
    {
      id: 'mock-turismo-sucre',
      title: 'Novedad turistica en Sucre',
      description: 'Se promueven recorridos patrimoniales en el centro historico.',
      source: 'MAPIA demo',
      url: null,
      publishedAt,
      locationText: 'Sucre, Bolivia',
      lat: -19.0196,
      lng: -65.2619,
      category: 'noticia',
      createdBy: 'ia',
      locationStatus: 'mock',
    },
  ];
}
