name: mapiafrontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.6.0
  http_parser: ^4.0.0
  google_maps_flutter: ^2.17.1
  geolocator: ^14.0.3
  image_picker: ^1.2.2
  speech_to_text: ^7.4.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  record: ^6.2.1
  path_provider: ^2.1.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/src/pinguino de chill.png
    - lib/src/pinguino registrandose.png
